listen {
    port 1883
    protocol mqtt
    tcp_nodelay true
}

allow_anonymous true
log_level warning
storage_dir /var/lib/flashmq

client_initial_buffer_size 4194304
max_packet_size 1048576
max_qos_msg_pending_per_client 65535
thread_count 2
