#!/usr/bin/env python3
"""
gen_bridge_conf.py — generate FlashMQ bridge config from bridge.yaml

Usage:
    python3 gen_bridge_conf.py [bridge.yaml] [--output path/to/bridge.conf]

If --output is not given, prints to stdout.
The output file should be loaded by FlashMQ via:
    include_dir /etc/flashmq/bridge-conf.d/
in your main flashmq.conf.

After updating bridge.yaml, regenerate and reload:
    python3 gen_bridge_conf.py bridge.yaml --output /etc/flashmq/bridge-conf.d/bridge.conf
    flashmq --reload-config
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml


def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def resolve_groups(bridge_groups: list, all_groups: dict, bridge_name: str) -> list[tuple[str, int]]:
    """Return list of (topic, qos) pairs for the named groups."""
    result = []
    for group_name in bridge_groups:
        if group_name not in all_groups:
            print(f"WARNING: bridge '{bridge_name}' references unknown group '{group_name}'", file=sys.stderr)
            continue
        group = all_groups[group_name]
        for topic in group.get("topics", []):
            result.append(topic)
    return result


def render_bridge_block(name: str, conn: dict, topics: list[str]) -> str:
    lines = []
    lines.append(f"# Bridge: {name}")
    if desc := conn.get("description"):
        lines.append(f"# {desc}")
    lines.append("bridge {")

    lines.append(f"    address {conn['host']}")
    lines.append(f"    port {conn.get('port', 1883)}")

    if proto := conn.get("protocol_version"):
        lines.append(f"    protocol_version {proto}")

    if kv := conn.get("keepalive"):
        lines.append(f"    keepalive {kv}")

    if prefix := conn.get("clientid_prefix"):
        lines.append(f"    clientid_prefix {prefix}")

    # PyYAML parses bare 'on'/'off' as booleans — normalise to string
    tls_raw = conn.get("tls", "off")
    tls = {True: "on", False: "off"}.get(tls_raw, str(tls_raw))
    if tls != "off":
        lines.append(f"    tls {tls}")
        if ca := conn.get("ca_file"):
            lines.append(f"    ca_file {ca}")

    if user := conn.get("remote_username"):
        lines.append(f"    remote_username {user}")
    if pw := conn.get("remote_password"):
        lines.append(f"    remote_password {pw}")

    if "remote_clean_start" in conn:
        lines.append(f"    remote_clean_start {str(conn['remote_clean_start']).lower()}")

    qos = conn.get("qos", 1)
    lines.append("")
    lines.append(f"    # Topics ({len(topics)} from {len(conn.get('groups', []))} group(s))")
    for topic in topics:
        lines.append(f"    publish {topic} {qos}")

    lines.append("}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate FlashMQ bridge config from bridge.yaml")
    parser.add_argument("config", nargs="?", default="bridge.yaml", help="Path to bridge.yaml")
    parser.add_argument("--output", "-o", help="Write output to this file (default: stdout)")
    parser.add_argument("--bridge", help="Only generate config for this bridge name")
    args = parser.parse_args()

    cfg = load_config(args.config)
    groups = cfg.get("groups", {})
    bridges = cfg.get("bridges", {})

    if not bridges:
        print("No bridges defined in config.", file=sys.stderr)
        sys.exit(0)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    blocks = [
        f"# Auto-generated by gen_bridge_conf.py — {generated}",
        f"# Source: {args.config}",
        "# Do not edit — regenerate with: python3 gen_bridge_conf.py bridge.yaml",
        "",
    ]

    for name, conn in bridges.items():
        if args.bridge and name != args.bridge:
            continue

        topics = resolve_groups(conn.get("groups", []), groups, name)
        if not topics:
            print(f"WARNING: bridge '{name}' resolved to 0 topics — skipping", file=sys.stderr)
            continue

        blocks.append(render_bridge_block(name, conn, topics))
        blocks.append("")

    output = "\n".join(blocks)

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(output)
        print(f"Written {out} ({len(topics)} topics across {len(bridges)} bridge(s))")
    else:
        print(output)


if __name__ == "__main__":
    main()
